name: "Terraform Apply (Prod)"

# This only runs when code is actually merged into the main branch
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out Engine into a side-by-side subfolder
      - name: Checkout Metadata Engine
        uses: actions/checkout@v4
        with:
          path: kc-metadata-engine-v2
        
      # 2. Check out Governance into a side-by-side subfolder
      - name: Checkout App Governance
        uses: actions/checkout@v4
        with:
          repository: DKNetzer/kc-app-governance-v2
          path: kc-app-governance-v2

      # 3. Authenticate securely to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/351374086012/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'tf-github-sa@jutomate-playground-hub.iam.gserviceaccount.com'

      # 4. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      # 5. Run Terraform Init
      - name: Terraform Init
        working-directory: ./kc-metadata-engine-v2
        run: terraform init -upgrade -backend-config=environments/dev/backend.tfvars
        
      # 6. Run Terraform Apply (The -auto-approve flag is critical for automation!)
      - name: Terraform Apply
        working-directory: ./kc-metadata-engine-v2
        run: terraform apply -var-file=environments/dev/terraform.tfvars -auto-approve